### ISSUE TITLE
Create CPP code for Bubble Sort algorithm

### ISSUE THREAD

**Issue by Kunal-Attri** [Kunal-Attri/algorithms#2]
Need to create CPP code for bubble sort algorithm in Bubble Sort folder

**Comment by marooncoder09** [comment]
hey! I want to contribute to this project

**Comment by marooncoder09** [comment]
Can you please elaborate further on what I have to do.

**Comment by Kunal-Attri** [comment]
Go ahead @marooncoder09 
So, We have a Bubble Sort folder here, which needs a file in CPP, with Bubble sort algorithm in it. So just create a new CPP file named bubblesort.cpp and write the code for it, and create a PR.

**Comment by Kunal-Attri** [comment]
You can also check Python version also, CPP file should be similar working.

**Comment by marooncoder09** [comment]
Thanks a lot @Kunal-Attri Consider it to be done!

**Comment by VictoriousMango** [comment]
i would like to try too...

**Comment by Kunal-Attri** [comment]
Go ahead @VictoriousMango 
Read instructions from above

**Comment by marooncoder09** [comment]
@Kunal-Attri is there anything else I can help you out with..?
